### ISSUE TITLE
How can I get the whole essays and ruburics?

### ISSUE THREAD

**Issue by venzino-han** [samlee946/ICLE-PlusPlus#1]
It appears that only annotation files exist in the current repository.
Where can I get the data for the full essays and rubrics?

**Comment by samlee946** [comment]
Thank you for your interests in our work! 

The essays are distributed by Presses universitaires de Louvain and can be obtained here: https://uclouvain.be/en/research-institutes/ilc/cecl/iclev2.html

The rubrics are listed in our paper, specifically Table 1 and Tables 14-23. For a more detailed discussion for the rubrics, we refer you to our previous work:
https://aclanthology.org/D10-1023/
https://aclanthology.org/P13-1026/
https://aclanthology.org/P14-1144/
https://aclanthology.org/P15-1053/

**Comment by venzino-han** [comment]
@samlee946 Thanks for your help!
